name: Uptime Monitor

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pyyaml jinja2

      - name: Run uptime monitor
        run: python monitor.py

      - name: Check for changes
        id: changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data.json incident.yaml index.html
          if git diff --cached --exit-code; then
            echo "No changes to commit"
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "Changes detected"
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      - name: Commit data
        if: env.no_changes == 'false'
        run: |
          git commit -m "Update uptime data and incident reports"

      - name: Push changes
        if: env.no_changes == 'false'
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git remote set-url origin https://$PAT@github.com/${{ github.repository }}
          git push origin main
