name: Uptime Monitor

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests pyyaml jinja2
      - name: Run uptime monitor
        run: python monitor.py
      - name: Commit data
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data.json incident.yaml status.html
          git commit -m "Update uptime data and incident reports"
      - name: Push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git remote set-url origin https://$PAT@github.com/${{ github.repository }}
          git push origin main
